server:
  port: 8082
Spring:
  application:
  datasource:
    username: root
    password: 558666
    url: jdbc:mysql://localhost:3306/house?serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev
      #设置返回日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    lettuce:
      pool:
        min-idle: 0
        max-wait: 6
        max-active: 8
        max-idle: 8
    host: 192.168.111.129
    port: 6379
    database: 0
    timeout: 1000
    password: 558666
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/lgq/House/mapper/xml/*.xml
